export const animais = [
  {
    id: 1,
    nome: "Luna",
    minibio: "Luna é uma gatinha carinhosa e cheia de vida que adora brincar com bolinhas e se aconchegar nos cobertores durante os dias frios. Sua curiosidade é infinita, sempre explorando cada cantinho da casa, o que faz dela uma verdadeira aventureira doméstica. Ela é muito afetuosa com as pessoas da casa, gosta de atenção e faz companhia nos momentos de descanso. Luna também tem uma personalidade calma e sabe se adaptar bem a diferentes ambientes e rotinas.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78760.jpeg",
    especie: "gato",
    raca: "Siamês",
    idade: 2,
    sexo: "fêmea",
    porte: "pequeno",
    castrado: true,
    vacinado: true
  },
  {
    id: 2,
    nome: "Thor",
    minibio: "Thor é um gato persa elegante e muito tranquilo, que conquista todos com sua presença serena. Ele gosta de longos cochilos ao sol e demonstra um olhar profundo e calmo que transmite paz. Sua pelagem macia é um convite para carinhos, e ele aprecia momentos de sossego ao lado de seus humanos. Thor é ideal para quem busca um companheiro reservado, que não exige muita agitação e preza pelo conforto e rotina.",
    imagem: "/images/elegant-black-cat-portrait.jpg",
    especie: "gato",
    raca: "Persa",
    idade: 4,
    sexo: "macho",
    porte: "pequeno",
    castrado: false,
    vacinado: true
  },
  {
    id: 3,
    nome: "Mimi",
    minibio: "Mimi é uma Maine Coon dócil e extremamente sociável, que adora longas sessões de carinho e atenção. Ela tem uma personalidade extrovertida, se dando muito bem com outros animais e pessoas. Mimi é uma verdadeira brincalhona, sempre pronta para interagir e animar o ambiente. Sua pelagem exuberante e porte médio fazem dela um gato imponente, mas com um temperamento doce e equilibrado, perfeito para quem busca uma companhia alegre e carinhosa.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78761.jpeg",
    especie: "gato",
    raca: "Maine Coon",
    idade: 3,
    sexo: "fêmea",
    porte: "médio",
    castrado: true,
    vacinado: false
  },
  {
    id: 4,
    nome: "Rex",
    minibio: "Rex é um Sphynx curioso, cheio de energia e com uma personalidade vibrante. Ele adora explorar cada canto da casa e tem uma inteligência aguçada, o que o torna muito interativo e receptivo a brinquedos e desafios. Rex é carinhoso e gosta de estar perto das pessoas, buscando companhia e atenção constantes. Apesar de não ter pelos, ele compensa com uma presença marcante e afetuosa, tornando-se um animal de estimação único e muito especial.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78758.jpeg",
    especie: "gato",
    raca: "Sphynx",
    idade: 1,
    sexo: "macho",
    porte: "pequeno",
    castrado: true,
    vacinado: true
  },
  {
    id: 5,
    nome: "Bella",
    minibio: "Bella é uma Ragdoll calma e encantadora, que gosta de passar o dia descansando e recebendo carinho. Sua personalidade doce e tranquila faz dela uma ótima companhia para ambientes familiares e momentos relaxantes. Ela é uma gatinha que adora o conforto do lar e se sente à vontade em qualquer espaço, sempre pronta para um colo ou uma carícia. Bella é ideal para quem busca um gato pacífico e afetuoso, que traz harmonia para o dia a dia.",
    imagem: "/images/gato5.jpg",
    especie: "gato",
    raca: "Ragdoll",
    idade: 5,
    sexo: "fêmea",
    porte: "médio",
    castrado: false,
    vacinado: true
  },
  {
    id: 6,
    nome: "Simba",
    minibio: "Simba é um gato siberiano brincalhão, cheio de vida e muito companheiro. Ele adora atividades ao ar livre e é conhecido por seu temperamento equilibrado e carinhoso, que conquista a todos que o conhecem. Simba gosta de explorar a natureza, mas também aprecia momentos de descanso aconchegado. Sua pelagem densa e bonita requer cuidados, mas ele retribui com muita amizade e lealdade. Um verdadeiro parceiro para quem gosta de uma companhia ativa e afetuosa.",
    imagem: "/images/gato6.jpg",
    especie: "gato",
    raca: "Siberiano",
    idade: 3,
    sexo: "macho",
    porte: "grande",
    castrado: true,
    vacinado: true
  },
  {
    id: 7,
    nome: "Buddy",
    minibio: "Buddy é um Labrador alegre e cheio de energia, que adora correr, brincar na água e fazer novos amigos. Ele é extremamente leal e está sempre pronto para acompanhar seu humano em aventuras ao ar livre. Buddy tem um temperamento amigável e extrovertido, tornando-o o parceiro ideal para famílias ativas e amantes da natureza. Sua presença contagiante alegra qualquer ambiente, e ele demonstra um amor incondicional pelo seu círculo social.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78752.png",
    especie: "cachorro",
    raca: "Labrador",
    idade: 4,
    sexo: "macho",
    porte: "grande",
    castrado: true,
    vacinado: true
  },
  {
    id: 8,
    nome: "Lola",
    minibio: "Lola é uma Poodle inteligente e cheia de energia, que adora aprender novos truques e estar sempre em movimento. Sua capacidade de adaptação e o desejo de agradar fazem dela uma excelente companheira para quem gosta de desafios e atividades diárias. Lola é afetuosa e sociável, além de ser muito leal à sua família. Seu porte pequeno não diminui a sua vitalidade, tornando-a uma presença vibrante e encantadora em qualquer lar.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78753.jpeg",
    especie: "cachorro",
    raca: "Poodle",
    idade: 2,
    sexo: "fêmea",
    porte: "pequeno",
    castrado: false,
    vacinado: true
  },
  {
    id: 9,
    nome: "Rocky",
    minibio: "Rocky é um Bulldog Francês cheio de personalidade, brincalhão e muito companheiro. Apesar do tamanho compacto, ele tem muita energia e é extremamente afetuoso com sua família. Rocky adora estar perto das pessoas, participando ativamente do dia a dia da casa. Sua expressão charmosa e jeito carismático conquistam facilmente quem o conhece, tornando-o um cachorro ideal para quem busca um amigo fiel e divertido.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78754.jpeg",
    especie: "cachorro",
    raca: "Bulldog Francês",
    idade: 3,
    sexo: "macho",
    porte: "médio",
    castrado: true,
    vacinado: false
  },
  {
    id: 10,
    nome: "Maya",
    minibio: "Maya é uma Golden Retriever dócil e gentil, que ama crianças e é perfeita para famílias ativas. Ela se destaca pela paciência e pelo carinho que demonstra, sendo uma excelente amiga para todos em casa. Maya gosta de longas caminhadas e atividades ao ar livre, mas também sabe ser calma e acolhedora nos momentos de descanso. Sua presença traz alegria e conforto, fazendo dela uma companheira ideal para diversas situações e ambientes.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78756.jpeg",
    especie: "cachorro",
    raca: "Golden Retriever",
    idade: 5,
    sexo: "fêmea",
    porte: "grande",
    castrado: false,
    vacinado: true
  },
  {
    id: 11,
    nome: "Fred",
    minibio: "Fred é um Beagle curioso e ativo, sempre explorando o ambiente com seu olfato apurado em busca de novas aventuras. Ele tem muita energia e adora passeios e brincadeiras, sendo um ótimo companheiro para pessoas que gostam de atividades ao ar livre. Fred é também muito inteligente e afetuoso, estabelecendo vínculos fortes com sua família. Sua personalidade alegre faz dele um animal de estimação divertido e carinhoso.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78757.jpeg",
    especie: "cachorro",
    raca: "Beagle",
    idade: 3,
    sexo: "macho",
    porte: "médio",
    castrado: true,
    vacinado: true
  },
  {
    id: 12,
    nome: "Nina",
    minibio: "Nina é uma Shih Tzu muito carinhosa e dedicada, que adora ficar perto de seus donos e recebe todos com muita alegria. Sua personalidade doce e tranquila conquista facilmente quem a conhece, tornando-a uma ótima companheira para ambientes familiares. Apesar de seu porte pequeno, Nina tem uma presença marcante e um temperamento amigável. Ela é perfeita para quem busca um cachorro calmo e amoroso, que preza pelo contato humano constante.",
    imagem: "/images/freepik__the-style-is-candid-image-photography-with-natural__78755.jpeg",
    especie: "cachorro",
    raca: "Shih Tzu",
    idade: 2,
    sexo: "fêmea",
    porte: "pequeno",
    castrado: false,
    vacinado: false
  }
];
